---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: examples
spec:
  owner: guests
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: example-website
spec:
  type: website
  lifecycle: experimental
  owner: guests
  system: examples
  providesApis: [example-grpc-api]
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: share-holder-info-api
  description: API to fetch all shareholder information.
  tags:
    - rest
    - springboot
spec:
  type: openapi
  lifecycle: production
  owner: team-a
  system: examples
  definition:
    $text: https://raw.githubusercontent.com/abddisa/backStageTest/main/openapi.yaml
