openapi: 3.0.1
servers:
  - url: https://api.spotify.com/v1
info:
  title: Bunna Bank API
  version: 2021.4.2
  x-apisguru-categories:
    - media
  x-logo:
    url: https://logo-core.clearbit.com/spotify.com
  x-origin:
    - format: openapi
      url: https://raw.githubusercontent.com/sonallux/spotify-web-api/master/spotify-web-api-generator-open-api/spotify-web-api-openapi.yml
      version: "3.0"
  x-providerName: bunnabank.com
  x-unofficialSpec: true
tags:
  - description: Albums API
    name: category-albums
  - description: Artists API
    name: category-artists

paths:
  /albums:
    get:
      description: Get Spotify catalog information for multiple albums identified by
        their Spotify IDs.
      operationId: endpoint-get-multiple-albums
      security:
        - spotify_auth: []
      summary: Get Multiple Albums
      tags:
        - category-albums
        
  "/albums/{id}":
    get:
      description: Get Spotify catalog information for a single album.
      operationId: endpoint-get-an-album
      security:
        - spotify_auth: []
      summary: Get an Album
      tags:
        - category-albums
  "/albums/{id}/tracks":
    get:
      description: |-
        Get Spotify catalog information about an album's tracks.
        Optional parameters can be used to limit the number of tracks returned.
      operationId: endpoint-get-an-albums-tracks
      security:
        - spotify_auth: []
      summary: Get an Album's Tracks

 
      
      tags:
        - category-browse
  /search:
    get:
      description: >-
        Get Spotify Catalog information about albums, artists, playlists,
        tracks, shows or episodes

        that match a keyword string.
      operationId: endpoint-search
      security:
        - spotify_auth: []
      summary: Search for an Item
    
      tags:
        - category-playlists
	  
	  
  securitySchemes:
    spotify_auth:
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.spotify.com/authorize
          scopes:
            app-remote-control: Remote control playback of Spotify. This scope is currently
              available to Spotify iOS and Android SDKs.
            playlist-modify-private: Write access to a user's private playlists.
            playlist-modify-public: Write access to a user's public playlists.
            playlist-read-collaborative: Include collaborative playlists when requesting a user's playlists.
            playlist-read-private: Read access to user's private playlists.
            streaming: Control playback of a Spotify track. This scope is currently
              available to the Web Playback SDK. The user must have a Spotify
              Premium account.
            ugc-image-upload: Write access to user-provided images.
            user-follow-modify: Write/delete access to the list of artists and other users
              that the user follows.
            user-follow-read: Read access to the list of artists and other users that the
              user follows.
            user-library-modify: Write/delete access to a user's "Your Music" library.
            user-library-read: Read access to a user's library.
            user-modify-playback-state: Write access to a user’s playback state
            user-read-currently-playing: Read access to a user’s currently playing content.
            user-read-email: Read access to user’s email address.
            user-read-playback-position: Read access to a user’s playback position in a content.
            user-read-playback-state: Read access to a user’s player state.
            user-read-private: Read access to user’s subscription details (type of user account).
            user-read-recently-played: Read access to a user’s recently played tracks.
            user-top-read: Read access to a user's top artists and tracks.
          tokenUrl: https://accounts.spotify.com/api/token
      type: oauth2
