openapi: 3.0.0
info:
  title: Share Holder Info API
  version: 1.0.0
  description: Endpoint to retrieve all shareholder information.
servers:
  - url: http://localhost:8083
paths:
  /api/account/cardReq/getCardList?accountNumber=2439501000599:
    get:
      summary: Get all shareholder info
      operationId: getAllShareHolders
      tags:
        - ShareHolder
      responses:
        '200':
          description: A list of shareholder info
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    shares:
                      type: number
