apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-a
  description: Team A — owns customer-facing APIs
spec:
  type: team
  profile:
    displayName: Team A
    email: team-a@example.com
  members: []
