site_name: Share Holder Info API Docs
docs_dir: docs
site_dir: site

plugins:
  - techdocs-core  # Required for Backstage TechDocs
  - mkdocs-techdocs-core  # Also required (merged into one list)

nav:
  - Home: index.md

theme:
  name: material
