site_name: Share Holder Info API Docs
docs_dir: docs  # Explicitly set docs directory
site_dir: site  # Explicit output directory

nav:
  - Home: index.md

plugins:
  - mkdocs-techdocs-core

theme:
  name: material
