site_name: Share Holder Info API Docs

nav:
  - Home: index.md
  # Remove usage.md reference since it doesn't exist
  # Add other pages here as you create them

plugins:
  - mkdocs-techdocs-core

theme:
  name: material

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - fenced_code
