apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: share-holder-info-api
  description: API to fetch all shareholder information.
  tags:
    - rest
    - share-system
    - springboot
  annotations:
    backstage.io/techdocs-ref: dir:./  # Add trailing slash
    backstage.io/source-location: url:https://github.com/abddisa/backStageTest/tree/main/share-holder-info-api
spec:
  type: openapi
  lifecycle: production
  owner: team-a
  system: share-system
  definition:
    $text: https://raw.githubusercontent.com/abddisa/backStageTest/main/openapi.yaml
